# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: integration tests

on:
  push:
    branches: [ master, feature/it-tests ]
  pull_request:
    branches: [ master, release-1.3.5 ]
  workflow_dispatch:
    inputs:
    branches: [ master, release-1.3.5 ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      # The 'verify' phase is the needed one for running integration tests
      run: mvn -Pintegration-tests -q clean verify
